spring:
  application:
    name: catalog-service
  data:
    elasticsearch:
      repositories:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  elasticsearch:
    uris: http://localhost:9200
    socket-timeout: 30s
    connection-timeout: 10s
    rest:
      headers:
        Content-Type: "application/vnd.elasticsearch+json;compatible-with=8"
        Accept: "application/vnd.elasticsearch+json;compatible-with=8"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false # Optional: keeps the JSON clean for other services

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  oltp:
    matrics:
      export:
        enabled: false
  defaults:
    metrics:
      export:
        enabled: false
otel:
  service:
    name: catalog-service
  resource:
    attributes:
      service.name: catalog-service
logging:
  pattern:
    # This specific format is what the OTEL starter looks for to inject IDs
    level: "%5p [${spring.application.name:-}, %X{traceId:-}, %X{spanId:-}]"