
spring:
  ai:
    openai:
      api-key: '${API-KEY}'
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      pgvector:
        intialize-schema: true
        index-type: HNSW
        distance-type: COSINE-DISTANCE
        dimensions: 1536
  cloud:
    compatibility-verifier:
      enabled: false
    instance:
      status-page-url-path: /actuator/info
      health-check-url-path: /actuator/health
      prefer-ip-address: true
  threads:
    virtual:
      enabled: true
  reactor:
    context-propagation: AUTO
  application:
    name: catalog-service
  data:
    redis:
      host: redis
    elasticsearch:
      repositories:
        enabled: true
  datasource:
    url: jdbc:postgresql://catalog_db:5434/catalog_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  elasticsearch:
    uris: elasticsearch:9200
    socket-timeout: 30s
    connection-timeout: 10s
    rest:
      headers:
        Content-Type: "application/vnd.elasticsearch+json;compatible-with=8"
        Accept: "application/vnd.elasticsearch+json;compatible-with=8"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
  kafka:
    template:
      observation-enabled: true
    bootstrap-servers: kafka-broker:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false # Optional: keeps the JSON clean for other services
        interceptor.classes: io.opentelemetry.instrumentation.kafkaclients.v2_6.TracingProducerInterceptor

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  oltp:
    matrics:
      export:
        enabled: false
  defaults:
    metrics:
      export:
        enabled: false
otel:
  service:
    name: catalog-service
  resource:
    attributes:
      service.name: catalog-service
logging:
  pattern:
    # This specific format is what the OTEL starter looks for to inject IDs
    level: "%5p [${spring.application.name:-}, %X{traceId:-}, %X{spanId:-}]"
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/