server:
  port: 8084

spring:
  application:
    name: recommendation-service
  threads:
    virtual:
      enabled: true

catalog:
  service:
    url: ${CATALOG_SERVICE_URL:http://catalog-service:8081}

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka-container:8761/eureka/
  instance:
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health