spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://order_db:5432/order_db
    username: user
    password: password
  kafka:
    bootstrap-servers: kafka-broker:9092
    template:
      default-topic: order-events
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      consumer:
        properties:
          spring.json.trusted.packages: "*"
          isolation.level: read_uncommitted
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/


